--REFERENCING
ALTER TABLE STUDENTS.LIBRARYCARD_DETAILS
ADD CONSTRAINT CARDNUMBER_FK FOREIGN KEY(CARDNUMBER)
REFERENCES STUDENTS.LIBRARYPAYMENT(ID)
ON UPDATE CASCADE
ON DELETE CASCADE


--- SECURITIES ON TABLES
CREATE TABLE BOOK.AUTHOR(
ID INT  PRIMARY KEY,
[NAME] VARCHAR(30) CHECK(LEN(NAME)>1) NOT NULL,
)
--- ADDING FOREIGN KEY TO THE DB
ALTER TABLE BOOK.CONTENT
ADD FOREIGN KEY (ID)
REFERENCES BOOK.AUTHOR(ID)

ALTER TABLE BOOK.DETAILS
ADD FOREIGN KEY (ID)
REFERENCES BOOK.AUTHOR(ID)

ALTER TABLE BOOK.LOG
ADD FOREIGN KEY (ID)
REFERENCES BOOK.AUTHOR(ID)

ALTER TABLE BOOK.PUBLISHER
ADD FOREIGN KEY (ID)
REFERENCES BOOK.AUTHOR(ID)

ALTER TABLE STUDENTS.BORROWERSCARD
ADD FOREIGN KEY (ID)
REFERENCES STUDENTS.BOOK_COLLECTIONS(STUDENT_ID)


ALTER TABLE STUDENTS.DETAILS
ADD FOREIGN KEY (ID)
REFERENCES STUDENTS.BOOK_COLLECTIONS(STUDENT_ID)


ALTER TABLE STUDENTS.LIBRARYCARD_DETAILS
ADD FOREIGN KEY (ID)
REFERENCES STUDENTS.BOOK_COLLECTIONS(STUDENT_ID)


ALTER TABLE STUDENTS.LIBRARYPAYMENT
ADD FOREIGN KEY (ID)
REFERENCES STUDENTS.BOOK_COLLECTIONS(STUDENT_ID)


ALTER TABLE STUDENTS.LIBRARYUSAGE
ADD FOREIGN KEY (ID)
REFERENCES STUDENTS.BOOK_COLLECTIONS(STUDENT_ID)



ALTER TABLE STUDENTS.BOOK_COLLECTIONS
ADD PRIMARY KEY(STUDENT_ID)

ALTER TABLE STUDENTS.BORROWERSCARD
ADD PRIMARY KEY(ID)






