create database [LIBRARY MANAGEMENT]
USE [LIBRARY MANAGEMENT]
CREATE SCHEMA BOOK
CREATE TABLE BOOK.DETAILS(
ID INT PRIMARY KEY,
TITLE VARCHAR(30) NOT NULL,
BOOK_TYPE VARCHAR(30) NOT NULL,
)

CREATE TABLE BOOK.AUTHOR(
ID INT  PRIMARY KEY,
[NAME] VARCHAR(30) CHECK(LEN(NAME)>1) NOT NULL,
)

DROP TABLE BOOK.AUTHOR
CREATE TABLE BOOK.PUBLISHER(
ID INT PRIMARY KEY,
PUBLISHERS_NAME VARCHAR(30),
ISBN INT 
)

CREATE TABLE BOOK.CONTENT(
ID INT PRIMARY KEY,
NO_OF_PAGES INT,
)
ALTER TABLE BOOK.CONTENT
ADD CONSTRAINT ID_FK FOREIGN KEY(ID)
REFERENCES BOOK.AUTHOR(ID)

CREATE TABLE BOOK.[LOG](
ID INT PRIMARY KEY,
DATE_OF_PURCHASE DATE,
DATE_OF_ENTRY DATE,
BOOK_COLLECTOR_NAME VARCHAR(30)
)